---
#node service
apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
