apiVersion: v1
kind: Pod
metadata:
  name: workload
spec: 
  containers:
  - name: sise
    image: bootjp/wrk2
    ports:
    - containerPort: 9876
    command: ['/bin/sh']
    args: []
  terminationGracePeriodSeconds: 10


